### ISSUE TITLE
How do I know if there was an error in a test run?

### ISSUE THREAD

**Issue by magestican** [adflynn/webrtc-troubleshooter#5]
Looking at the examples errors are logged into the console but the runAllTests function does not return any error of the added tests.

Is it possible to get errors in any way?

**Comment by adflynn** [comment]
The Test class, which all Tests inherit from (and can be found in TestSuite.js) has this construtor
```
  constructor (options, callback) {
    this.options = options || {};
    this.callback = callback || _.noop;
    this.logger = this.options.logger || console;
  }
```
the logger you provide when creating the tests can be one that outputs to wherever you like, the default is the console.

**Comment by magestican** [comment]
That was very useful, works perfectly, thanks
